/* DO NOT EDIT THIS FILE - it is machine generated */
#define __int64 int64_t
#include <jni.h>
/* Header for class org_shoco_Shoco */
#ifndef _Included_org_shoco_Shoco
#define _Included_org_shoco_Shoco
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_shoco_Shoco
 * Method:    compress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_shoco_Shoco_compress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_shoco_Shoco
 * Method:    decompress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_shoco_Shoco_decompress
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
